### ISSUE TITLE
您好，请教您一个问题

### ISSUE THREAD

**Issue by ixuhan** [MrzhangF1ghter/mp3player#1]
由于之前没接触过RTT，请教您一个问题。看了一下RTT的框架，它有一套audio的driver，如果接入这一套就需要去实现audio的ops从而给应用层使用。但是该mp3player为啥没有用audio的接口，而去调用pcm的一套。也就是说如果我需要使用mp3player需要再挂载一套pcm的io驱动实现pcm_write/read是么？也不知道表达清楚没有，谢谢。

**Comment by MrzhangF1ghter** [comment]
您好，这个组件是基于audio框架的，你需要实现声卡的驱动，我的组件只是往audio写，可以参考一下https://github.com/RT-Thread/rt-thread/tree/master/bsp/stm32/stm32l475-atk-pandora,该bsp有板载声卡的实现。我这边有TAS5805的声卡驱动，近期整理后会上传。

**Comment by ixuhan** [comment]
刚刚没有仔细阅读RTT的驱动框架，现在搞懂了，再次感谢。
